### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by vaultec81** [vaultec81/3Speak-app#1]
Video player:
- [ ] Next video button
- [ ] Video recommendations as seen in the main 3Speak site.
- [ ] Custom offline first player at some point in the future. With support for all current features in Jwplayer (webm, HLS, mp4, etc)

Local content cacher:
- [ ] Indexing posts from list of followers

Account system: 
- [ ] Local private key encryption
- [ ] Orbitdb account system
- [ ] Ability to bind accounts together
- [ ] Commenting, upvote, downvote, etc.
- [ ] Service node account graph sync. 
- [ ] Export account + pins + following to file for moving to another device.

Distributed communities:
- [ ] Binding hive communities to distributed communities
- [ ] Multi administrator support
- [ ] Ensure no duplicate posts on hive and orbitdb community

Video uploader:
- [ ] FFmpeg local encoding
- [ ] Webm-vp9 option
- [ ] Hardware acceleration option
- [ ] Ability to add custom files such as webvtt captions.
- [ ] Thumbnail support
- [ ] IPFS cache wait lock. Ensure video has been cached on atleast 1 other node before proceeding to upload. Includes temporary upload acceleration servers.
- [ ] Communities support

Other important notes:
- Service node roadmap will be in a separate repo.
- [ ] Seed based orbitdb keypairs (https://github.com/orbitdb/orbit-db-identity-provider/pull/60)
